name: s3

on: [push, pull_request]

jobs:
  s3:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: s3 with ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: whywaita/actions-cache-s3@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          aws-s3-bucket: ${{secrets.AWS_S3_BUCKET_NAME}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          # aws-region: us-east-1

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests
